# Generated by Django 6.0.4 on 2026-04-20 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='Category', max_length=150)),
                ('name_bn', models.CharField(default='ক্যাটাগরি', max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='description',
            new_name='description_bn',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_bn',
            field=models.CharField(default='শিরোনাম', max_length=150),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_en',
            field=models.CharField(default='Title', max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='name_bn',
            field=models.CharField(default='অজানা', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='name_en',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.location'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='News Title', max_length=150)),
                ('title_bn', models.CharField(default='খবরের শিরোনাম', max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='news/')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.location')),
            ],
        ),
    ]
