# Generated by Django 6.0.4 on 2026-04-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_location_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
    ]
