# Generated by Django 6.0.4 on 2026-04-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_location_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
