# Generated by Django 6.0.4 on 2026-04-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
