# Generated by Django 6.0.4 on 2026-04-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_news_is_breaking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrandingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='News Title', max_length=150)),
                ('title_bn', models.CharField(default='খবরের শিরোনাম', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='news/')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
