# Generated by Django 6.0.4 on 2026-04-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_companyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='location',
            new_name='location_bn',
        ),
        migrations.RenameField(
            model_name='companyinfo',
            old_name='mobile_no',
            new_name='mobile_no_bn',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='location_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mobile_no_en',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
