# Generated by Django 6.0.4 on 2026-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_rename_location_companyinfo_location_bn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
