# Generated by Django 6.0.4 on 2026-04-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trandingnews',
            name='title_bn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trandingnews',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
