# Generated by Django 6.0.4 on 2026-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_tag_name_tag_name_bn_tag_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
