# Generated by Django 6.0.4 on 2026-04-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_comment_user_commentreply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='name',
        ),
    ]
